apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables"
clusterCIDR: "10.200.0.0/16"
metricsBindAddress: "0.0.0.0:10249"
clientConnection:
  kubeconfig: /var/lib/kube-proxy/kubeconfig
iptables:
  masqueradeAll: false
  syncPeriod: 30s
  minSyncPeriod: 5s
ipvs:
  strictARP: false
