#cloud-config
preserve_hostname: false
hostname: ${hostname}
fqdn: ${hostname}.kthw.lab
manage_etc_hosts: true

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - linux-modules-extra-aws
  - chrony
  - conntrack
  - socat
  - iptables
  - iptables-persistent
  - nfs-common
  - curl
  - jq
  - unzip
  - apt-transport-https
  - ca-certificates

write_files:
  - path: /etc/modules-load.d/kubernetes.conf
    permissions: '0644'
    owner: root:root
    content: |
      overlay
      br_netfilter
      nf_conntrack
  - path: /etc/sysctl.d/99-kubernetes.conf
    permissions: '0644'
    owner: root:root
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
      vm.swappiness = 0
  - path: /etc/kthw/node-role
    permissions: '0644'
    owner: root:root
    content: |
      role=${role}
      hostname=${hostname}

runcmd:
  - [ bash, -c, 'swapoff -a' ]
  - [ bash, -c, "sed -ri 's/(.*swap.*)/#\\1/' /etc/fstab" ]
  - [ modprobe, overlay ]
  - [ modprobe, br_netfilter ]
  - [ modprobe, nf_conntrack ]
  - [ sysctl, --system ]
  - [ systemctl, enable, --now, chrony.service ]
