apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter10-nginx
  labels:
    app: chapter10-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chapter10-nginx
  template:
    metadata:
      labels:
        app: chapter10-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - /bin/sh
            - -c
            - |
              cat <<EON >/usr/share/nginx/html/index.html
              Served by ${NODE_NAME} (${NODE_IP})
              EON
              exec nginx -g 'daemon off;'
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/os: linux
