apiVersion: v1
kind: Pod
metadata:
  name: metrics-server-debug
  namespace: kube-system
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: metrics-server
  containers:
    - name: debug
      image: public.ecr.aws/docker/library/busybox:1.36.1
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: client-cert
          mountPath: /etc/metrics-server/certs
          readOnly: true
        - name: kubeconfig
          mountPath: /etc/metrics-server/kubeconfig
          readOnly: true
  volumes:
    - name: client-cert
      secret:
        secretName: metrics-server-client-cert
    - name: kubeconfig
      secret:
        secretName: metrics-server-kubeconfig
