apiVersion: v1
kind: Pod
metadata:
  name: dns-metrics-check
  namespace: default
  labels:
    app: dns-metrics-check
spec:
  containers:
    - name: busybox
      image: public.ecr.aws/docker/library/busybox:1.36.1
      command:
        - sleep
        - "3600"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
  restartPolicy: Never
