apiVersion: v1
kind: Pod
metadata:
  name: dns-metrics-check
  namespace: default
  labels:
    app: dns-metrics-check
spec:
  containers:
    - name: agnhost
      image: registry.k8s.io/e2e-test-images/agnhost:2.45
      command:
        - sleep
        - "3600"
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
  restartPolicy: Never
