apiVersion: v1
kind: Pod
metadata:
  name: dns-metrics-check
  namespace: default
  labels:
    app: dns-metrics-check
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.35
      command:
        - sh
        - -c
        - sleep 3600
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
  restartPolicy: Never
